languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "@wan0net"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[author]
   name = "Iain Dickson"
   image = "img/author.jpg"
   headline = "@wan0net - Cyber Solutions Architect"
   bio = "Iain is the Full Spectrum Cyber Practice Lead for Leidos Australia, and provides oversight and support to all of Leidos' AU programs for technical cyber security. He has worked across a number of critical federal government programs, including delivering security operations capabilities, large enterprise scale software systems, a breadth of other enterprise IT services and more recently military platforms.  He has previously worked as a Cyber Research Engineer and as an Assistant Director for Cyber Threat Intelligence within the Department of Defence. He is also one of the founders of ComfyCon AU, a virtual conference founded as a direct response to the cancellation of cyber security conferences due to the COVID-19 pandemic."
   links = [
     { email = "mailto:icd@wan0.net" },
     { linkedin = "https://linkedin.com/in/wan0net" },
     { discord = "https://discord.gg/invitecode" },
     { github = "https://github.com/wan0net" },
     { reddit = "https://reddit.com/user/username" },
     { slack = "https://workspace.url/team/userid" },
     { steam = "https://steamcommunity.com/profiles/wan0net" },
     { x-twitter = "https://twitter.com/wan0net" },
   ]
