languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "@wan0net"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[author]
   name = "Iain Dickson - @wan0net"
   image = "img/author.jpg"
   headline = "Part Time Tater Tot Leader for ComfyCon AU, Full Time Cyber Solutions Architect"
   bio = "A little bit about you"
   links = [
     { email = "mailto:icd@wan0.net" },
     { linkedin = "https://linkedin.com/in/wan0net" },
     { discord = "https://discord.gg/invitecode" },
     { github = "https://github.com/wan0net" },
     { reddit = "https://reddit.com/user/username" },
     { slack = "https://workspace.url/team/userid" },
     { steam = "https://steamcommunity.com/profiles/wan0net" },
     { x-twitter = "https://twitter.com/wan0net" },
   ]
