enableImageLazyLoading = true

[author]
  name = "Iain Dickson"
  image = "img/author.jpg"
  handle = "wan0net"
  headline = "I didn't do it. Nobody saw me do it. You can't prove anything."

  [[author.links]]
    platform = "email"
    url = "mailto:icd@wan0.net"

  [[author.links]]
    platform = "linkedin"
    url = "https://linkedin.com/in/wan0net"

  [[author.links]]
    platform = "x-twitter"
    url = "https://twitter.com/wan0net"

  [[author.links]]
    platform = "github"
    url = "https://github.com/wan0net"

  [[author.links]]
    platform = "discord"
    url = "https://discord.gg/xCkgjmGzTr"

  [[author.links]]
    platform = "steam"
    url = "https://steamcommunity.com/id/wan0net/"

  [[author.links]]
    platform = "ko-fi"
    url = "https://ko-fi.com/wan0net"
