# Site settings
title: "Iain Dickson"
email: icd@wan0.net
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "wan0.net"
title_description: "Iain is the Full Spectrum Cyber Practice Lead for Leidos Australia, and provides oversight and support to all of Leidos' AU programs for technical cyber security. He has worked across a number of critical federal government programs, including delivering security operations capabilities, large enterprise scale software systems, a breadth of other enterprise IT services and more recently military platforms.  He has previously worked as a Cyber Research Engineer and as an Assistant Director for Cyber Threat Intelligence within the Department of Defence. He is also one of the founders of ComfyCon AU, a virtual conference founded as a direct response to the cancellation of cyber security conferences due to the COVID-19 pandemic."
title_image: "https://gravatar.com/avatar/f6d237b276117be15944a3b2a939e98e?s=500&d=mm"
github_repository: https://github.com/wan0net/wan0net.github.io
post_limit: 5

# Social usernames/URLs
twitter_username: wan0net
github_username:  wan0net
linkedin_link: https://linkedin.com/in/wan0net
mastodon_link: https://infosec.exchange/@wan0net
# Footer

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
